### ISSUE TITLE
Call functions from namespace

### ISSUE THREAD

**Issue by vathymut** [Thie1e/cutpointr#13]
Hi,
Thank you so much for `cutpointr`.  

It's more a question than a bug, perhaps. I may have missed something obvious, but when I call `cutpointr` functions from its namespace (as I would for inclusion in my own package), I get an error. Here's my minimal reproducible example:

``` r
library(cutpointr)
#> Warning: package 'cutpointr' was built under R version 3.5.2
opt_cut_namespace <- cutpointr::cutpointr_(
  suicide,
  "dsi",
  "suicide",
  method = cutpointr::minimize_boot_metric,
  metric = cutpointr::false_omission_rate
)
#> Assuming the positive class is yes
#> Assuming the positive class has higher x values
#> Error in `$<-.data.frame`(`*tmp*`, "method", value = c("::", "cutpointr", : replacement has 3 rows, data has 1
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
#> [3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=English_Canada.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] cutpointr_0.7.4
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.18     knitr_1.20       bindr_0.1.1      magrittr_1.5    
#>  [5] tidyselect_0.2.4 R6_2.2.2         rlang_0.2.1      foreach_1.4.4   
#>  [9] stringr_1.3.1    dplyr_0.7.6      tools_3.5.1      iterators_1.0.10
#> [13] htmltools_0.3.6  yaml_2.2.0       rprojroot_1.3-2  digest_0.6.15   
#> [17] assertthat_0.2.0 tibble_1.4.2     crayon_1.3.4     bindrcpp_0.2.2  
#> [21] tidyr_0.8.1      purrr_0.2.5      codetools_0.2-15 glue_1.3.0      
#> [25] evaluate_0.11    rmarkdown_1.10   stringi_1.1.7    compiler_3.5.1  
#> [29] pillar_1.3.0     backports_1.1.2  pkgconfig_2.0.1
```
What's the recommended way, if any, to do this? Thanks again.

Best,
V.

**Comment by Thie1e** [comment]
Hi, 
thanks for reporting this issue and for the kind words! This was indeed a simple bug in the way `cutpointr` tried to fetch the name of the `method` function.

There are two ways of dealing with this problem:

1. Import `minimize_boot_metric` via the NAMESPACE file. If you are using `roxygen`, you can simply do so with `#' @importFrom cutpointr minimize_boot_metric`.

2. Install the current version of `cutpointr` (v0.7.6) that includes the bugfix from Github with `devtools::install_github("thie1e/cutpointr)`. This is of course not a good option, if you want to upload your package to CRAN soon.

**Comment by vathymut** [comment]
Great - thanks for the quick answer. I've opted for option (2)  as v0.7.6 includes `metric_constrain` and other neat features.
