### ISSUE TITLE
Auto-select numeric columns in multi_cutpointr

### ISSUE THREAD

**Issue by xrobin** [Thie1e/cutpointr#16]
If I run `multi_cutpointr` on the `suicide` dataset without specifying `x`,  I get the following error on a non-numeric column:

```
multi_cutpointr(suicide, class = "suicide")
age:
Assuming the positive class is no
Assuming the positive class has higher x values
gender:
Error in median.default(x[class == uc[1]]) : need numeric data

```

It is common to have non-numeric columns  with different groupings etc. that may not be used right now. Just like the gender column. It would be a nice addition to auto-detect numeric columns only.

**Comment by Thie1e** [comment]
Hi, thanks for the suggestion, I think that's a good idea and I've added that feature to the current version on Github, so `multi_cutpointr(suicide, class = "suicide")` should now run without any problems. 

If the new default of `x = NULL` is kept, an internal function is called that fetches the names of all numeric columns.

**Comment by xrobin** [comment]
Works great!

**Comment by Thie1e** [comment]
Glad to hear that!
