### ISSUE TITLE
Re-upload to CRAN

### ISSUE THREAD

**Issue by xrobin** [Thie1e/cutpointr#26]
I don't know if you are aware of it already, but I just noticed that [cutpointr was removed from CRAN](https://cran.r-project.org/web/packages/cutpointr/index.html) a few days ago.

**Comment by Thie1e** [comment]
Hi, thanks - yes, I'm aware of that. We had minor problems with the new release of `tibble` (I think some functions started producing messages) but version 3.0.0 of `tibble` has just arrived on CRAN and `cutpointr` will be back on CRAN very soon. We'll bump the required versions of some of our dependencies then.

**Comment by krlmlr** [comment]
I'm sorry the tibble update may have triggered the removal from CRAN. Let me know if I can help.

**Comment by Thie1e** [comment]
Thanks for reaching out. We're back on CRAN since Tuesday. `tibble` just gave us a 'new names' message which made some tests fail. I think we also got a message from `ggplot2` when running it the first time, but I don't get it when using the package outside of `testthat`, so I'm not sure what the problem was.

**Comment by d-lamb** [comment]
cutpointr was removed from CRAN again, perhaps on 15 June.  I don't have enough expertise to help diagnose, but thought you'd like to be aware in case you missed it.

**Comment by Thie1e** [comment]
Hi, thanks for the reminder. I'm sorry for that. We've submitted cutpointr 1.0.3, which is the version currently on Github and compatible with dplyr 1.0.0, to CRAN two weeks ago. I'll try to get it sorted out.

**Comment by Thie1e** [comment]
We're on our way to CRAN again now with version 1.0.32. Everything user-facing is identical to 1.0.3. Sorry for the inconvenience and thanks again for calling my attention to this.

**Comment by d-lamb** [comment]
Thanks for being so prompt!  Much appreciated.
