### ISSUE TITLE
Plot a the ROC curve with manual settings

### ISSUE THREAD

**Issue by jo1511** [Thie1e/cutpointr#47]
Sorry, but I'm quite a newbie here and I don't know if this is really the right place to ask.

I wanted to just plot the ROC curve with the cutpoint and a vertival and horizontal line at the cutpoint.
In addition, I wanted to change the appearance of the cutpoint and the lines (ROC, vline, hline) with regard to type, size/with and color. I also wanted to print the AUC value and the cutpoint values into the graph.

However, I failed and finally I don't have any idea what to do with the tibbles. Can anyone help me please!

Many thanks in advance!

Jo1511

**Comment by jo1511** [comment]
Great, many thanks for your fast reply, everything worked well with my data!!!

Just one, probably easy question, if you don't mind.
I used the youden metric with OptimalCutpoints and cutpointr and they gave the same results.
However, when I used the MinValueSp metric with OptimalCutpoints I was not quite sure which metric to use in cutpointr. 
I tried spec_constrain and minimize_metric, but that did not give the same results. 

Again sorry for my stupidity:-(

Jo1511

**Comment by Thie1e** [comment]
Hi, no problem. I think it is the other way around: 

- `MinValueSp` in `OptimalCutpoints` maximizes **sensitivity** given a minimum value of specificity given in something like `control = control.cutpoints(valueSp = 0.8)`
- `spec_constrain` in `cutpointr` optimizes (depending on the chosen function for `method`) the **specificity** given a minimum value of another metric, such as sensitivity. For example: `constrain_metric = sensitivity, min_constrain = 0.8`

If you want to maximize sensitivity given a minimum value for specificity in `cutpointr` that would be something like:

```
cutpointr(suicide, dsi, suicide, 
                metric = sens_constrain, 
                method = maximize_metric,
                pos_class = "yes", direction = ">=",
                constrain_metric = specificity, min_constrain = 0.8)
```

**Comment by jo1511** [comment]
Ok, got it, and worked well!
Many thanks again, you made my day!

jo1511
