### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kormilitzin** [Thie1e/cutpointr#5]
The package looks very exciting, however, when I run the following code, I get the error:
```
> install.packages('cutpointr')
Warning in install.packages :
  package ‘cutpointr’ is not available (for R version 3.4.3)
```

My machine:

> sessionInfo()
>
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.4 LTS

Any ideas?

**Comment by Thie1e** [comment]
Hi, cutpointr was built using the current version of R (3.4.4). Can you try again after upgrading? If you're on Ubuntu, you should be able to do so with `apt update` and `apt upgrade`.

**Comment by kormilitzin** [comment]
Hi, thanks, I will try to update my R version.
