### ISSUE TITLE
Creating a composite biomarker score using regression coefficients 

### ISSUE THREAD

**Issue by LauraL231** [Thie1e/cutpointr#58]
Hello,

I wanted to create a composite biomarker score of 4 markers that I can then enter into further predictive analysis. I was planning on doing this by extracting the β coefficients from the multivariable logistic regression with all (standardized) biomarkers and then multiply those with the (standardized) biomarker levels to create a composite. I just wondered whether this method was ok and how I can go about this using R?

Thanks,
Laura

**Comment by Thie1e** [comment]
Hi Laura, 

I guess you could surely build a "standard" logistic regression model the way you described it using `glm`, for example. 

But it seems to me this question does not directly relate to `cutpointr`. Generally, if you calculate cutpoints for your markers, just make sure **not** to feed dichotomized marker values into your regression model. 

You can estimate a cutpoint on the resulting probabilities from the logistic regression model, if you are interested in diagnostic accuracy.

I would suggest to post a question to stats.stackexchange.com if you have a purely methodological / statistical question or to StackOverflow if you can't get the R code to work (questions directly related to `cutpointr` can of course still go here).

Best,
Christian

**Comment by LauraL231** [comment]
Thanks very much for the information, that's really helpful to know.
Thanks,
Laura
