### ISSUE TITLE
change colors and theme using plot()

### ISSUE THREAD

**Issue by luisebe** [Thie1e/cutpointr#68]
Dear all, 

thank you for the great package, it is really easy to use and the documentation is nice. 

I do have one issue: I would like to customize the colors in the plot() output, I tried exporting the gTree object to ggplot and I tried the as.ggplot function, both unsuccessful. 

Could you help me out here? thanks!
best, 
Luise

below is my code: 

cp <- cutpointr(data = dat, 
                x = value, 
                class = cutoff, 
                subgroup = sex,
                direction = ">=",
                method = oc_youden_kernel, 
                pos_class = "positive", 
                neg_class = "negative",
                na.rm = TRUE)
summary(cp)
plot(cp)

**Comment by Thie1e** [comment]
Hi, 

thanks for the positive words. The output of `plot()` is a composition of multiple individual plot functions:

- plot_x()
- plot_roc()
- plot_cut_boot()
- plot_metric_boot()

These individual functions return `ggplot` objects that are easier to modify. For example:

``` r
library(cutpointr)
library(tidyverse)

cp <- cutpointr(data = suicide,
                x = dsi,
                class = suicide,
                method = maximize_metric,
                metric = sum_sens_spec,
                subgroup = gender,
                na.rm = TRUE)
#> Assuming the positive class is yes
#> Assuming the positive class has higher x values

roc_plot <- cutpointr::plot_roc(cp) +
     scale_color_viridis_d() +
     theme_minimal() +
     coord_equal()

class_plot <- cutpointr::plot_x(cp) +
     scale_color_viridis_d() +
     scale_fill_viridis_d() +
     theme_minimal() +
     theme(legend.position="none") 

library(patchwork)
class_plot + roc_plot
```

![](https://i.imgur.com/InXrsbE.png)

<sup>Created on 2024-12-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by luisebe** [comment]
great, this helped a lot - thanks for your fast reply!
